### ISSUE TITLE
error parsing cleverbot responses?

### ISSUE THREAD

**Issue by japherwocky** [japherwocky/j4ne#10]
```
Traceback (most recent call last):
  File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/japherwocky/j4ne/networks/deescord.py", line 73, in on_message
    await self.on_message(message)
  File "/home/japherwocky/j4ne/networks/deescord.py", line 115, in on_message
    reply = self.CB.say(query)
  File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/cleverwrap/cleverwrap.py", line 60, in say
    reply = self._send(params)
  File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/cleverwrap/cleverwrap.py", line 78, in _send
    return r.json()
  File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 2179 (char 2178)
```

**Comment by japherwocky** [comment]
should be fixed with cl3ver
