### ISSUE TITLE
discord disconnections!

### ISSUE THREAD

**Issue by japherwocky** [japherwocky/j4ne#11]
```
[E 170413 02:31:22 ioloop:633] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f48e84e26a8>, <tornado.concurrent.Future
object at 0x7f48e84fa7f0>)
    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/selector_events.py", line 669, in _read_ready
        data = self._sock.recv(self.max_size)
    ConnectionResetError: [Errno 104] Connection reset by peer

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/aiohttp/client.py", line 202, in _request
        yield from resp.start(conn, read_until_eof)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 640, in start
        message = yield from httpstream.read()
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/aiohttp/streams.py", line 641, in read
        result = yield from super().read()
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/aiohttp/streams.py", line 476, in read
        yield from self._waiter
      File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
    aiohttp.errors.ServerDisconnectedError

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/tornado/ioloop.py", line 604, in _run_callback
        ret = callback()
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/tornado/ioloop.py", line 619, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
        result = coro.throw(exc)
      File "/home/japherwocky/j4ne/networks/deescord.py", line 79, in connect
        await client.start(discord_token)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/discord/client.py", line 491, in start
        yield from self.connect()
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/discord/client.py", line 452, in connect
        self.ws = yield from DiscordWebSocket.from_client(self, resume=resume)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/discord/gateway.py", line 174, in from_client
        gateway = yield from client.http.get_gateway()
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/discord/http.py", line 578, in get_gateway
        data = yield from self.get(self.GATEWAY, bucket=_func_())
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/discord/http.py", line 105, in request
        r = yield from self.session.request(method, url, **kwargs)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/aiohttp/client.py", line 555, in __iter__
        resp = yield from self._coro
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/aiohttp/client.py", line 209, in _request
        raise aiohttp.ClientResponseError() from exc
    aiohttp.errors.ClientResponseError
```

a bit later in the logs, related?

```
[E 170413 02:40:50 base_events:1148] Task exception was never retrieved
    future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /home/japherwocky/j4ne/env/lib/python3.5/site-packages/websockets/protocol.py:407> exception=ConnectionResetError(104, 'Connection reset by peer')>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
        result = coro.throw(exc)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/websockets/protocol.py", line 413, in run
        msg = yield from self.read_message()
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/websockets/protocol.py", line 435, in read_message
        frame = yield from self.read_data_frame(max_size=self.max_size)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/websockets/protocol.py", line 490, in read_data_frame
        frame = yield from self.read_frame(max_size)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/websockets/protocol.py", line 525, in read_frame
        self.reader.readexactly, is_masked, max_size=max_size)
      File "/home/japherwocky/j4ne/env/lib/python3.5/site-packages/websockets/framing.py", line 80, in read_frame
        data = yield from reader(2)
      File "/usr/lib/python3.5/asyncio/streams.py", line 670, in readexactly
        block = yield from self.read(n)
      File "/usr/lib/python3.5/asyncio/streams.py", line 627, in read
        yield from self._wait_for_data('read')
      File "/usr/lib/python3.5/asyncio/streams.py", line 457, in _wait_for_data
        yield from self._waiter
      File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/selector_events.py", line 669, in _read_ready
        data = self._sock.recv(self.max_size)
    ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by japherwocky** [comment]
maybe fixed with https://github.com/japherwocky/j4ne/blob/master/j4ne.py#L207-L222
